apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-web-config
data:
  VITE_APP_NAME: {{ .Values.config.VITE_APP_NAME | quote }}
  VITE_ENV: {{ .Values.config.VITE_ENV | quote }}
  VITE_API_GATEWAY_URL: {{ .Values.config.VITE_API_GATEWAY_URL | quote }}