frontend-web:
  replicaCount: 1

api-gateway:
  replicaCount: 1

user-service:
  replicaCount: 1

pet-service:
  replicaCount: 1

appointment-service:
  replicaCount: 1

order-service:
  replicaCount: 1

notification-service:
  replicaCount: 1

postgres:
  storage:
    size: 1Gi

mongodb:
  storage:
    size: 1Gi

kgateway:
  enabled: true

  namespace: prod

  gateway:
    name: happy-paws-gateway
    gatewayClassName: kgateway
    listenerName: http
    protocol: HTTP
    port: 80

  route:
    name: happy-paws-route
    hostnames:
      - happypaws.com
      - www.happypaws.com