replicaCount: 1

image:
  repository: mongo
  tag: "7"
  pullPolicy: IfNotPresent

service:
  port: 27017

containerPort: 27017

storage:
  size: 5Gi
  storageClassName: nfs-storage

resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

secret:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: password