# charts/frontend-web/values.yaml

replicaCount: 2

image:
  repository: likhithabhogyam/happy-paws-frontend
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

containerPort: 80

strategy:
  maxUnavailable: 1
  maxSurge: 1

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

config:
  VITE_APP_NAME: Happy Paws
  VITE_ENV: production
  VITE_API_GATEWAY_URL: /api

probes:
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10

  liveness:
    path: /
    initialDelaySeconds: 15
    periodSeconds: 20